AWSTemplateFormatVersion: '2010-09-09'
Description: FinScope AWS infrastructure - S3 (frontend) and RDS MySQL (DB)

Parameters:
  AppName:
    Type: String
    Default: finscope
  EnvironmentName:
    Type: String
    Default: prod
  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppName}-${EnvironmentName}-frontend-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: ['s3:GetObject']
            Resource: !Sub '${FrontendBucket.Arn}/*'

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds: []  # TODO: fill with your subnet IDs or create via console

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      EngineVersion: '8.0'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      DBName: finscope
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: true
      VPCSecurityGroups: []  # TODO: attach security group that allows MySQL from EB
      DBSubnetGroupName: !Ref DBSubnetGroup

Outputs:
  FrontendBucketName:
    Value: !Ref FrontendBucket
  RDSEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
